version: 0.4.7
image: Visual Studio 2019
clone_folder: c:\project
build_script:
- cmd: >-
    git submodule update --init --recursive

    dotnet restore

    dotnet publish -c Release -o c:\project\build\release PopStudio.WPF\PopStudio.WPF.csproj
artifacts:
- path: build/release
  name: release
- path: build/debug
  name: debug